version: "3.9"
services:
  kronleinbackend-server:
     build: kronleinbackend-server
     mem_limit: 350m
     environment:
        - SPRING_PROFILES_ACTIVE=docker
     ports:
        - "8080:8080"
     depends_on:
        kronleinbackend-db:
            condition: service_healthy
  kronleinbackend-db:
     build: kronleinbackend-db
     environment:
        - POSTGRES_PASSWORD=postgres
     ports:
        - "5432:5432"
     healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 10
